fleet_save_module.main.time=off19:50?10M-19:59
sleep_module.main.time=off21:00?10M-23:59
expedition_module.main.time=off
clear_module.main.time=off19:00-19:59
build_module.main.time=on03:32-18:00
swarn_module.main.time=off07:50-19:39
space_module.main.time=off19:00-19:49

expedition_module.expedition_day.time=off
expedition_module.expedition_night.time=on
expedition_module.expedition_night.ships=transporterLarge:10,explorer:1,battleship:1

sleep_module.sleep.speed=30

update.time=on
update.refresh=6M?3M

build_module.build_planet.time=on
#directiveiv;small;base
build_module.build_planet.list=directiveiv;mines_14_14_12_15_1
build_module.build_forms.time=off
#mechat1;mechat2;mechat3;humanst1;humanst2;kaelesht1;kaelesht2;rocktalt1;rocktalt2
build_module.build_forms.list=humanst1
build_module.build_moon.time=off
build_module.build_moon.list=fastteleport

##########################################################################
main.time=on
define.fly_points=
consumer.source=none
define.transporterSmall=5000

main.template=templates/global.properties
fleet_save_module.main.template=templates/fleet_save.properties
sleep_module.main.template=templates/sleep.properties
expedition_module.main.template=templates/expedition.properties
space_module.main.template=templates/space.properties
clear_module.main.template=templates/clean.properties
build_module.main.template=templates/build.properties
swarn_module.main.template=templates/swarn.properties

consumer.login=<login>
consumer.password=<password>
consumer.server=<server_name>
consumer.url=<url>
