##########################################################################
main.time=on
define.fly_points=
define.transporterSmall=5000

fleet_save_module.main.template=../template/fleet_save.properties
sleep_module.main.template=../template/sleep.properties
clear_module.main.template=../template/clean.properties
build_module.main.template=../template/build.properties
expedition_module.main.template=../template/expedition.properties
space_module.main.template=../template/space.properties
swarn_module.main.template=../template/swarn.properties
main.template=../snark/template/global.properties


main.login=<login>
main.password=<password>
main.server=<server_name>
