##########################################################################
main.time=on
define.fly_points=
define.transporterSmall=5000

fleet_save_module.main.template=../templates/fleet_save.properties
sleep_module.main.template=../templates/sleep.properties
clear_module.main.template=../templates/clean.properties
build_module.main.template=../templates/build.properties
expedition_module.main.template=../templates/expedition.properties
space_module.main.template=../templates/space.properties
swarn_module.main.template=../templates/swarn.properties
main.template=../snark/templates/global.properties


main.login=<login>
main.password=<password>
main.server=<server_name>
