build_planet.time=03:32-18:00
build_planet.list=base;mines_38_32_34_32_20
build_planet.source=planets

build_moon.time=03:32-18:00
build_moon.source=moons
build_moon.list=fastteleport

build_forms.time=03:32-18:00
build_forms.list=mechat1;mechat2;mechat3
build_forms.source=planets