main.time=on

move_ships_to_moon.time=on
move_ships_to_moon.source=planets
move_ships_to_moon.target=swap
move_ships_to_moon.leave_ships_wave=transporterLarge:3000,explorer:2,battleship:1

move_resources_to_moon.time=on
move_resources_to_moon.source=planets
move_resources_to_moon.target=swap
move_resources_to_moon.mission=transport
move_resources_to_moon.start_conditions=[{"type":"RESOURCE_COUNT","planet":"source","resourcesCount":"3m"}]
move_resources_to_moon.expired_time=back
move_resources_to_moon.resources=all

move_ships_to_planet.time=on
#move_ships_to_planet.condition_ships_in_source=transporterLarge:100,explorer:1
move_ships_to_planet.source=moons
move_ships_to_planet.target=swap
move_ships_to_planet.mission=stationed
move_ships_to_planet.ships_wave=transporterLarge:3000,explorer:2
move_ships_to_planet.expired_time=6H