expedition_day.time=03:22-19:00
expedition_day.source=moons
expedition_day.ships=transporterLarge:3000,explorer:1,battleship:1

expedition_night.time=19:01-07:55
expedition_night.source=planets
expedition_night.ships=transporterLarge:2000,explorer:1,battleship:1
expedition_night.pause=20S