fleet_save.time=on
fleet_save.source=#fly_points
#fleet_save.target=next
fleet_save.target=#prev(#source, #fly_points)
fleet_save.mission=STATIONED
fleet_save.start_conditions=[{"type":"SHIPS","planet":"source","shipsMap":"deathstar:10","leave":"none"}]
#sleep.trip=m[::];
#sleep.condition_ships_in_source=deathstar:1
#sleep.condition_blocking_missions=TRANSPORT;ATTACK;EXPEDITION
fleet_save.leave_ships_wave=deathstar:2,transporterLarge:20000,explorer:11,espionageProbe:1000
fleet_save.resources=all
fleet_save.leave_resources=d20m
fleet_save.speed=10
fleet_save.pause=10M