main.time=on
main.galaxy_max=9

consumer.time=on
consumer.source=moons
consumer.restart_duration=8M
#consumer.login=<login>
#consumer.password=<password>
#consumer.server=<server>
#consumer.url=<url>
consumer.driver=chromedriver.exe

defense.time=on
defense.alarm=sounds/alarm.wav
defense.recall=20M?10M

update.time=on
update.refresh=6M?3M

define.time=on
define.transporterSmall=-1
define.pause=1M