sleep.time=on
sleep.source=moons
sleep.target=next
sleep.mission=STATIONED
sleep.start_conditions=[{"type":"SHIPS","planet":"source","shipsMap":"deathstar:1","leave":"none"}, {"type":"NO_MISSIONS","source":"source","blockingMissions":"TRANSPORT;ATTACK;EXPEDITION"}]
#sleep.condition_ships_in_source=deathstar:1
#sleep.condition_blocking_missions=TRANSPORT;ATTACK;EXPEDITION
sleep.resources=all
sleep.leave_resources=nothing
sleep.speed=30