space.time=on
#space.range=7:230-280;6:30-120

#space.range=10
#space.coordinate=moons

#space.galaxy_max=9
space.command_limit=100
space.wrap_system=true
space.expired_time=P14D
space.pause=20M?10M

check.time=on
check.target=unknown
check.mission=SPY