
define_swarm.time=on
#define_swarm.swarm_nest=m[9:366:15]
define_swarm.swarm_nest=Colony|SELECT c.* FROM colonies c WHERE c.espionage_probe > 4000000 and c.type = 'MOON'
define_swarm.strategy=not_null
define_swarm.pause=1M

space.time=on
#space.galaxy_max=9
#space.range=9:351-352
space.range=51
space.coordinate=#cache_key('swarm_nest')
space.command_limit=4
space.wrap_system=true
space.expired_time=3H
#space.expired_time=P8D
space.spy_coordinate=#farm(#source)
space.spy_pattern=in_active
space.pause=4S

attack.time=on
attack.start_conditions=[{"type": "RESOURCE_COUNT","planet": "target","resourcesCount": "4kk"},{"type": "SPY_NOT_EXPIRED","seconds": 9900,"is": false,"target": "target"},{"type": "ATTACK_NOT_EXPIRED","seconds": 9900,"is": true,"target": "target"}]
attack.source=#cache_key('swarm_nest')
attack.target=#farm(#source)
attack.mission=ATTACK
attack.ships_wave=espionageProbe:-2
attack.speed=50
attack.command_limit=2
attack.expired_time=2H
attack.pause=4S

move.time=on
move.start_conditions=[{"type": "EXPRESSION","term": "swarn_module.attack_processing","operator": "eq","value": "DONE"}, {"type": "EXPRESSION","term": "swarn_module.space_processing","operator": "eq","value": "DONE"}, {"type":"NO_MISSIONS","source":"source","blockingMissions":"ATTACK"}]
move.source=#cache_key('swarm_nest')
move.target=#next(#source, #fly_points)
move.ships_wave=espionageProbe:all
move.leave_ships_wave=espionageProbe:1000
move.command_limit=1
move.speed=10
move.expired_time=6M
move.pause=2M
