package org.enoch.snark.instance.model.action.condition;

public enum ConditionType {
    RESOURCE_IN_SOURCE,
    RESOURCE_IN_TARGET,
    RESOURCES_COUNT_IN_SOURCE,
    RESOURCES_COUNT_IN_TARGET,
    SPY_IS_NOT_EXPIRED,
    SPY_IS_EXPIRED,
    ATTACK_IS_NOT_EXPIRED,
    ATTACK_IS_EXPIRED,
    SHIPS_IN_SOURCE,
    SHIPS_IN_TARGET,
    BLOCKING_MISSIONS,
    EXPEDITION
}
