create table colonies
(
  id          bigserial   not null
    constraint colonies_pkey
    primary key,
  galaxy      integer     not null,
  system      integer     not null,
  position    integer     not null,
  metal       bigint,
  crystal     bigint,
  deuterium   bigint,
  power       integer,
  level       integer,
  forms             text,
  forms_level       integer,
  updated    timestamp default now(),
  created       timestamp default now(),

  debris_metal       bigint,
  debris_crystal     bigint,
  debris_deuterium   bigint,

  cp          integer   not null,
  cpm          integer,
  type          text default 'PLANET',
  tags              text,

  -- fleet
  fighter_light    integer default 0,
  fighter_heavy    integer default 0,
  cruiser    integer default 0,
  battleship    integer default 0,
  interceptor   integer default 0,
  bomber   integer default 0,
  destroyer    integer default 0,
  deathstar    integer default 0,
  recycler    integer default 0,
  explorer    integer default 0,
  transporter_small    integer default 0,
  transporter_large    integer default 0,
  colony_ship   integer default 0,
  reaper   integer default 0,
  espionage_probe   integer default 0,
  sat   integer default 0,

  --defence
  rocket_launcher    integer default 0,
  laser_cannon_light   integer default 0,
  laser_cannon_heavy   integer default 0,
  gauss_cannon    integer default 0,
  ion_cannon    integer default 0,
  plasma_cannon    integer default 0,
  shield_dome_small   integer default 0,
  shield_dome_large   integer default 0,
  missile_interceptor    integer default 0,
  missile_interplanetary    integer default 0,

  -- Resources
  metal_mine             integer default 0,
  crystal_mine           integer default 0,
  deuterium_synthesizer  integer default 0,
  solar_plant            integer default 0,
  fusion_plant           integer default 0,
  solar_satellite        integer default 0,
  metal_storage          integer default 0,
  crystal_storage        integer default 0,
  deuterium_storage      integer default 0,

  --Facilities
  robotics_factory       integer default 0,
  shipyard              integer default 0,
  research_laboratory    integer default 0,
  alliance_depot         integer default 0,
  missile_silo           integer default 0,
  nanite_factory         integer default 0,
  terraformer           integer default 0,
  repair_dock            integer default 0,

  moonbase              integer default 0,
  sensor_phalanx         integer default 0,
  jump_gate              integer default 0,

  --Lifeform
  --Humans
  lifeform_tech11101 integer default 0,
  lifeform_tech11102 integer default 0,
  lifeform_tech11103 integer default 0,
  lifeform_tech11104 integer default 0,
  lifeform_tech11105 integer default 0,
  lifeform_tech11106 integer default 0,
  lifeform_tech11107 integer default 0,
  lifeform_tech11108 integer default 0,
  lifeform_tech11109 integer default 0,
  lifeform_tech11110 integer default 0,
  lifeform_tech11111 integer default 0,
  lifeform_tech11112 integer default 0,
-- Rock´tal
  lifeform_tech12101 integer default 0,
  lifeform_tech12102 integer default 0,
  lifeform_tech12103 integer default 0,
  lifeform_tech12104 integer default 0,
  lifeform_tech12105 integer default 0,
  lifeform_tech12106 integer default 0,
  lifeform_tech12107 integer default 0,
  lifeform_tech12108 integer default 0,
  lifeform_tech12109 integer default 0,
  lifeform_tech12110 integer default 0,
  lifeform_tech12111 integer default 0,
  lifeform_tech12112 integer default 0,
-- Mecha
  lifeform_tech13101 integer default 0,
  lifeform_tech13102 integer default 0,
  lifeform_tech13103 integer default 0,
  lifeform_tech13104 integer default 0,
  lifeform_tech13105 integer default 0,
  lifeform_tech13106 integer default 0,
  lifeform_tech13107 integer default 0,
  lifeform_tech13108 integer default 0,
  lifeform_tech13109 integer default 0,
  lifeform_tech13110 integer default 0,
  lifeform_tech13111 integer default 0,
  lifeform_tech13112 integer default 0,
-- Kaelesh
  lifeform_tech14101 integer default 0,
  lifeform_tech14102 integer default 0,
  lifeform_tech14103 integer default 0,
  lifeform_tech14104 integer default 0,
  lifeform_tech14105 integer default 0,
  lifeform_tech14106 integer default 0,
  lifeform_tech14107 integer default 0,
  lifeform_tech14108 integer default 0,
  lifeform_tech14109 integer default 0,
  lifeform_tech14110 integer default 0,
  lifeform_tech14111 integer default 0,
  lifeform_tech14112 integer default 0
);

create table targets
(
  id          bigserial   not null
    constraint targets_pkey
    primary key,
  galaxy      integer     not null,
  system      integer     not null,
  position    integer     not null,
  metal       bigint,
  crystal     bigint,
  deuterium   bigint,
  power       integer,
  player_id bigint not null references players,
  updated    timestamp default now(),
  created       timestamp default now(),
  last_attacked    timestamp,
  last_spied_on    timestamp,
  type        varchar(15) not null default 'PLANET',
  tags              text,

  debris_metal       bigint,
  debris_crystal     bigint,
  debris_deuterium   bigint,

  -- fleet
    fighter_light    integer default 0,
    fighter_heavy    integer default 0,
    cruiser    integer default 0,
    battleship    integer default 0,
    interceptor   integer default 0,
    bomber   integer default 0,
    destroyer    integer default 0,
    deathstar    integer default 0,
    recycler    integer default 0,
    explorer    integer default 0,
    transporter_small    integer default 0,
    transporter_large    integer default 0,
    colony_ship   integer default 0,
    reaper   integer default 0,
    espionage_probe   integer default 0,
    sat   integer default 0,

    --defence
    rocket_launcher    integer default 0,
    laser_cannon_light   integer default 0,
    laser_cannon_heavy   integer default 0,
    gauss_cannon    integer default 0,
    ion_cannon    integer default 0,
    plasma_cannon    integer default 0,
    shield_dome_small   integer default 0,
    shield_dome_large   integer default 0,
    missile_interceptor    integer default 0,
    missile_interplanetary    integer default 0,

    -- Resources
    metal_mine             integer default 0,
    crystal_mine           integer default 0,
    deuterium_synthesizer  integer default 0,
    solar_plant            integer default 0,
    fusion_plant           integer default 0,
    solar_satellite        integer default 0,
    metal_storage          integer default 0,
    crystal_storage        integer default 0,
    deuterium_storage      integer default 0,

    --Facilities
    robotics_factory       integer default 0,
    shipyard              integer default 0,
    research_laboratory    integer default 0,
    alliance_depot         integer default 0,
    missile_silo           integer default 0,
    nanite_factory         integer default 0,
    terraformer           integer default 0,
    repair_dock            integer default 0,

    moonbase              integer default 0,
    sensor_phalanx         integer default 0,
    jump_gate              integer default 0,

  --Lifeform
    --Humans
  lifeform_tech11101 integer default 0,
  lifeform_tech11102 integer default 0,
  lifeform_tech11103 integer default 0,
  lifeform_tech11104 integer default 0,
  lifeform_tech11105 integer default 0,
  lifeform_tech11106 integer default 0,
  lifeform_tech11107 integer default 0,
  lifeform_tech11108 integer default 0,
  lifeform_tech11109 integer default 0,
  lifeform_tech11110 integer default 0,
  lifeform_tech11111 integer default 0,
  lifeform_tech11112 integer default 0,
    -- Rock´tal
  lifeform_tech12101 integer default 0,
  lifeform_tech12102 integer default 0,
  lifeform_tech12103 integer default 0,
  lifeform_tech12104 integer default 0,
  lifeform_tech12105 integer default 0,
  lifeform_tech12106 integer default 0,
  lifeform_tech12107 integer default 0,
  lifeform_tech12108 integer default 0,
  lifeform_tech12109 integer default 0,
  lifeform_tech12110 integer default 0,
  lifeform_tech12111 integer default 0,
  lifeform_tech12112 integer default 0,
    -- Mecha
  lifeform_tech13101 integer default 0,
  lifeform_tech13102 integer default 0,
  lifeform_tech13103 integer default 0,
  lifeform_tech13104 integer default 0,
  lifeform_tech13105 integer default 0,
  lifeform_tech13106 integer default 0,
  lifeform_tech13107 integer default 0,
  lifeform_tech13108 integer default 0,
  lifeform_tech13109 integer default 0,
  lifeform_tech13110 integer default 0,
  lifeform_tech13111 integer default 0,
  lifeform_tech13112 integer default 0,
    -- Kaelesh
  lifeform_tech14101 integer default 0,
  lifeform_tech14102 integer default 0,
  lifeform_tech14103 integer default 0,
  lifeform_tech14104 integer default 0,
  lifeform_tech14105 integer default 0,
  lifeform_tech14106 integer default 0,
  lifeform_tech14107 integer default 0,
  lifeform_tech14108 integer default 0,
  lifeform_tech14109 integer default 0,
  lifeform_tech14110 integer default 0,
  lifeform_tech14111 integer default 0,
  lifeform_tech14112 integer default 0,

  resources   integer,
  fleet_sum   bigint default 0,
  defense_sum bigint default 0,
  spy_level integer default 4
);

create table targets_activity
(
  id          bigserial   not null
    constraint targets_activities_pkey
    primary key,
  target_id bigint not null references targets,
  counter       integer,
  tags              text,
  updated    timestamp default now()
);
